### ISSUE TITLE
point documentation links to official libuv docs

### ISSUE THREAD

**Issue by thlorenz** [thlorenz/learnuv#12]
The [official libuv docs](http://docs.libuv.org/) have majorly improved since this workshop was created.
I'm actually planning to deprecate the documentation part of [libuv-dox](https://github.com/thlorenz/libuv-dox) only keeping the examples.

Ideally all links to documentation in this workshop would point to the official uv documentation before I do that.

**Comment by coderkevin** [comment]
I have submitted a PR for this:  https://github.com/thlorenz/learnuv/pull/14

**Comment by thlorenz** [comment]
Fixed, thanks.
