### ISSUE TITLE
About items 'bufs' and 'bufsml[4]' in  uv_fs_t

### ISSUE THREAD

**Issue by bsdcpp** [thlorenz/learnuv#20]
Hi, everybody.
   Sorry to trouble you, but I got problem when I played with your 'games'. 
When I running my program(even your exercise answers), they all got "segmentation fault", I tracked them and found it should be here:
 /\* 4. Report the contents of the buffer */
  log_report("%s", read_req->bufs->base);
  log_info("%s", read_req->bufs->base);

because when it come into the callback, read_req->bufs turned to NULL, but I can use 
 read_req->bufsml->base to make it work.

**Comment by ChuntaoLu** [comment]
I run into the same "segmentation fault" too, have to define a static uv_buf_t `iov` then read and log that out to pass exercise 4.

**Comment by nicolaspanel** [comment]
@thlorenz : could you provide more info on this?
BR and thank you for the tutorial!

**Comment by fxrcode** [comment]
So as the rest of the exercises which need to get buf content?

**Comment by saghul** [comment]
the req->bufs and bufsml are not public fields, you shouldn't rely on them. Embed the uv_fs_t request into your own structure to keep track of the buffers. Same applies to uv_write_t for example.

**Comment by thlorenz** [comment]
Don't have bandwidth to look at this, but PRs are certainly welcome :)
