### ISSUE TITLE
Could I build on OSX without XCode?

### ISSUE THREAD

**Issue by juanarbol** [thlorenz/learnuv#31]
Runnig `./learnuv make` or `./learnuv ninja` is always asking for XCode

`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

**Comment by mpmckenna8** [comment]
If you're using a Mac with a Mac OS then to use the command line to do a lot of C related things you probably need to at least have the Xcode command line tools installed.  This will probably help with lots of other developer related things anyway so it's probably good to do. This can probably be done with https://www.embarcadero.com/starthere/berlin/mobdevsetup/ios/en/installing_the_xcode_command_line_tools_on_a_mac.html
